language: cpp
sudo: false
addons:
  apt:
    packages:
    - cmake
    - libxaw7-dev
    - libzzip-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libxt-dev
    - libboost-all-dev
    - libcppunit-dev
    - libgles2-mesa-dev
before_script:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install freetype libzzip cppunit cmake ; fi
osx_image: xcode7.1
env:
    - TEST=ON
script:
    # we only need the legacy GL rendersystem so tests work on the headless system
    - cmake -DOGRE_BUILD_TESTS=$TEST -DOGRE_BUILD_RENDERSYSTEM_GL=$TEST -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=$GL3 -DOGRE_BUILD_RENDERSYSTEM_GLES2=$GL3 -DCMAKE_BUILD_TYPE=Debug .
    - cmake --build .
    - if [ $TEST ]; then bin/Test_Ogre ; fi
os:
    - osx
cache: apt
