language: cpp
sudo: false
addons:
  apt:
    packages:
    - cmake
    - libxaw7-dev
    - libzzip-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libxt-dev
    - libboost-all-dev
    - libcppunit-dev
    - libgles2-mesa-dev
before_script:
    # we start compilation afterwards anyway, so no need to sleep
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start ; fi
    - if [ "$TRAVIS_OS_NAME" =   "osx" ]; then brew install freetype libzzip sdl2 cppunit cmake && gem install xcpretty ; fi
osx_image: xcode7.1
env:
    - TEST=TRUE
    - GL3ES=TRUE # build GL3Plus and GLES2 Rendersystems
    - ANDROID=TRUE
compiler:
    - clang
    - gcc
matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: osx
          compiler: gcc
        - os: osx
          env: TEST=TRUE
        - os: osx
          env: ANDROID=TRUE
script:
    - cmake -P ci-build.cmake
    - if [ "$TRAVIS_OS_NAME" !=   "osx" ]; then cmake --build . ; else set -o pipefail && cmake --build . | xcpretty  ; fi
    - if [ $TEST ]; then bin/Test_Ogre ; fi
os:
    - linux
    - osx
cache: apt
