language: cpp
sudo: required
dist: xenial
services:
    - xvfb
branches:
  only:
    - master
addons:
  apt:
    sources:
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial multiverse"
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe"
    packages:
    - cmake
    - libxaw7-dev
    - libzzip-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libxt-dev
    - libboost-all-dev
    - libgles2-mesa-dev
    - mesa-common-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev # legacy GL RenderSystem only
    - python3-dev
    - python3-lxml     # for validate script
    - nvidia-cg-dev
    - swig3.0
before_script:
    - if [ "$TRAVIS_OS_NAME" =   "osx" ]; then brew update && brew install freetype libzzip sdl2 ; fi
osx_image: xcode10.1
env:
    - TEST=TRUE
    - GL3ES=TRUE # build GL3Plus and GLES2 Rendersystems
    - ANDROID=TRUE
    - IOS=TRUE
compiler:
    - clang
    - gcc
matrix:
    exclude:
        - os: linux
          compiler: clang
        - os: linux
          env: IOS=TRUE
        - os: linux
          env: GL3ES=TRUE
        - os: osx
          compiler: gcc
        - os: osx
          env: TEST=TRUE
        - os: osx
          env: ANDROID=TRUE
script:
    - cmake -P ci-build.cmake
    - BUILD_CMD="cmake --build build"
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then BUILD_CMD="$BUILD_CMD -- -k -j 2" ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then BUILD_CMD="set -o pipefail && $BUILD_CMD | xcpretty" ; fi
    - echo $BUILD_CMD && eval $BUILD_CMD
    # run unit tests
    - if [ $TEST ]; then build/bin/Test_Ogre ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" -a "$IOS" != "TRUE" ]; then build/bin/Debug/Test_Ogre.app/Contents/MacOS/Test_Ogre ; fi
    # XMLConverter works & validates
    - if [ $TEST ]; then build/bin/OgreXMLConverter Samples/Media/models/jaiqua.mesh && build/bin/OgreXMLConverter Samples/Media/models/jaiqua.skeleton ; fi
    - if [ $TEST ]; then python3 Tools/XMLConverter/docs/validate.py Samples/Media/models/jaiqua.mesh.xml ; fi
    # run visual tests
    - if [ $TEST ]; then cd build/bin && ./TestContext -rs "OpenGL Rendering Subsystem" ; fi
    # verify that the python modules are loadable
    - if [ $TEST ]; then cd ../lib && python -c "import _Ogre; import _RTShader" ; fi
    # whitespace sanity
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git diff --check ${TRAVIS_COMMIT_RANGE/.../..} ; fi
os:
    - linux
    - osx
cache: apt
before_deploy:
    - if [ $ANDROID ]; then cd build/OgreJNI && zip -qr ogre-sdk-android-arm64-v8a.zip * ; fi
deploy:
  provider: bintray
  username: paroj
  skip_cleanup: true
  file: Other/bintray.json
  on:
    condition: $ANDROID
  key:
    secure: u2D7P92ZQQXyMEWeJdvVMhR1+DN58vyomvMZMYcfkE3HMUPynrQGNRP2tlUpQaTZy/uTOIaVnbn8joaix5I/FV8sJESEs2NiNuJ78UtVU2PKs3pj64fXU3surrG1ke70KAmEjFta02s35+NNk/yQNPJqjEEltbpoDYIoqXLEkz7LZwFLfI7lDoFhtV8UEx5GiAK/MdaTGbrMl4MK4LLkTySrJyULm2ZO0JBTGJS1eaL+dQm+seYmV+D536NtGHIRJ5PO+Ua1y0xkmqPQsF+zKkYyg8AoQcvs5EeTtoq0MltKmRFvRnPaciNAmMGmhVdC+gFv1w9lgAjh0747MV3iG2v6ZEJPpnNKpN/uGhJcn1NuPrvtTYqkw+R0rtuBQtBeFbO1ESZ9YRFhD4aG2tjACFOX0QVXneA648KwV7gKAFPIrFF6rG9we1oPFv9I26ym4FCUCdNkYXKd0zcZtBHPflrAxS1G6VgAzandjlVEPzkje1eDmfJt116hTlIkSwUk+1yOvJZ6sN4xKKkM3ibeFIARIR+Z8Q/LnMn91Y5p9HTo8PztMKunfN2LDffTizI6aP5ene6igUefiHA2QmVKLwXZJCjvteAsAqen3H+kZh/8oL/tW+BljP4nC0+hX7c5MP90udCRnhoTWc8kklEteSijVMSYSZkxV605l5aUyS8=
