platform: x64
configuration: Release
image: Visual Studio 2017

build:

build_script:
 - cmake -P ci-build.cmake
 - cmake --build .
 - bin\debug\Test_Ogre.exe
cache:
- ogredeps -> CMake/Dependencies.cmake
branches:
  only:
    - master
