platform: x64
configuration: Release
image:
 - Visual Studio 2017
 - Visual Studio 2013

environment: 
  APPVEYOR_RDP_PASSWORD: Ogre_Python#487
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3-x64
      RESTORE_MINICONDA: C:\Miniconda37-x64
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
 - cmd: choco install swig -y & exit 0
 - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
 - "set SWIG_DIR=%CONDA_PREFIX\\Lib\\bin"
 - "python --version"
 - conda update -y -q conda
 - conda info -a
 - conda create -y -q -n env_ogre python=%PYTHON_VERSION% numpy freetype swig
 - activate env_ogre
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
 - cmake -P ci-build.cmake
 - cmake --build build --config Release --target INSTALL

test_script:
 - set PATH=%PATH%;build\gtest\lib
 - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" build\bin\release\Test_Ogre.exe --gtest_filter=-MeshWithoutIndexDataTests*

after_test:
 - pip wheel Components/Python 

cache:
- ogredeps -> CMake/Dependencies.cmake

branches:
  only:
    - master
    - stable
artifacts:
  - path: build/sdk
    name: ogre-sdk-master-vc15-x64
  - path: dist\*.whl
    
# TODO: add wheels to build
# deploy:
# - provider: BinTray
#   username: paroj
#   api_key:
#     secure: 4nFEwKApbHUf7UajsDt6Z7QOl3zzgEz6YbWGSGx5AiPxozWEQHEyGc6c9xE7utWE
#   subject: ogrecave
#   repo: ogre
#   package: ogre-sdk-vc15-x64
#   publish: true
#   override: true
#   version: master
#   on:
#     branch: master
#     APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2017"
