platform: x64
configuration: Release
environment:
  CS_APIKEY:
    secure: XiSyqXBlbnIqawfinZqXimatuEdpYsI38+HK2TgvuUGHQEoeFHA62700/EhFJ4M1
image:
 - Visual Studio 2015
install:
 - cmd: SET PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
 - cmd: pip install swig==4.1.1
 - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs/
 - cmd: rustup-init.exe -y
 - cmd: curl -LO https://sdk.lunarg.com/sdk/download/1.2.189.2/windows/VulkanSDK-1.2.189.2-Installer.exe
 - cmd: VulkanSDK-1.2.189.2-Installer.exe --accept-licenses --default-answer --confirm-command install
 - cmd: cd %APPVEYOR_BUILD_FOLDER%
 - cmd: git submodule update --init --recursive
build_script:
 - set PATH=C:\Qt\6.2\msvc2019_64\bin;C:\Users\appveyor\.cargo\bin;%PATH%
 - set VULKAN_SDK=C:\VulkanSDK\1.2.189.2
 - cmake -P ci-build.cmake
 - cmake --build build --config RelWithDebInfo --target INSTALL
test_script:
 - set PATH=%PATH%;build\gtest\lib
 - build\bin\RelWithDebInfo\Test_Ogre.exe --gtest_filter=-MeshWithoutIndexDataTests*
cache:
- ogredeps -> CMake/Dependencies.cmake
branches:
  only:
    - master
    - stable
    - /v\d+\.\d+\.\d+/